name: Deploy admin blog

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # 切换分支
        uses: actions/checkout@main
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14.18.3
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.3'
          cache: 'npm'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # npm install
      - name: npm install
        run: |
          npm install

      # build
      - name: publish build
        run: |
          npm run build

      # tar
      - name: tar dist
        run: |
          tar zcf dist.tar.gz -C dist index.html

      #       # build
      #       - name: publish build
      #         run: |
      #           npm run publish
      #         env:
      #           CI: true

      - name: echo
        run: |
          echo ${{ secrets.ACCESS_TOKEN }}
          echo ${{ secrets.REMOTE_HOST }}
          echo ${{ secrets.REMOTE_USER }}
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist.tar.gz"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/wwwroot/admin-blogs'
