name: Deploy admin blog

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      # npm install
      - name: npm install
        run: |
          npm install

      # build
      - name: publish build
        run: |
          npm run build

      # tar
      - name: tar dist
        run: |
          tar zcf dist.tar.gz -C dist index.html

#       # build
#       - name: publish build
#         run: |
#           npm run publish
#         env:
#           CI: true

#       # Deploy
#       - name: Deploy
#         uses: easingthemes/ssh-deploy@v2.2.11
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
#           ARGS: "-avz --delete"
#           SOURCE: "dist/index.html"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.TARGET }}
